### ISSUE TITLE
90/180º heading rotation

### ISSUE THREAD

**Issue by willitcode** [frc937/robot2024#4]
Bind D-Pad buttons to rotate the robot by 90 or 180 degrees.

In field-oriented drive mode, this should rotate the robot relative to the field (duh). Pressing the left d-pad button should rotate the robot so that it faces towards the left side of the field, forward should face opposite DS wall, etc.

In robot-oriented drive mode, up and down should both flip the robot 180 degrees, left should rotate the robot 90 degrees to the left, and right should rotate the robot 90 degrees to the right.

This may require some extra legwork because changing the keymap based off of the drive base mode is a new one for us.

**Comment by willitcode** [comment]
YAGSL doesn't have built-in functionality for this, so we'll need to spend a bit more time implementing this. It's definitely doable though!

Feel free to brainstorm in this thread about how we could do it. I think we could probably abuse odometry to make it happen, or we could just turn in a direction until we hit the desired angle.

YAGSL has a built-in heading correction PID loop though, so I think a good bet is to grab the current robot pose, transform that pose to the desired rotation, and then ask odometry to move us to that pose. Only problem is that if the driver presses the d-pad while the robot is moving, it might do something weird.

YAGSL also has an example for how this can be implemented here: [https://github.com/BroncBotz3481/YAGSL-Example/blob/main/src/main/java/frc/robot/commands/swervedrive/drivebase/AbsoluteDriveAdv.java](https://github.com/BroncBotz3481/YAGSL-Example/blob/main/src/main/java/frc/robot/commands/swervedrive/drivebase/AbsoluteDriveAdv.java).

**Comment by Berdenson** [comment]
I think it would possibly be best to have the D-Pad assign an angle, and the robot turn to meet that angle. We could probably maybe even use cool trigonometric functions if they haven't implemented it. 
Either way, I think it may be worth it to have the robot turn according to the D-Pad in field-oriented terms even during robot-oriented. I think it would be more useful for the robot to turn relative to the field with the D-Pad rather than relative to the robot; to match up with the amp walls and whatnot. Of course this depends on whether or not we have field-oriented available at all times.

**Comment by willitcode** [comment]
Good point. We'll probably just want to consult with drive team, assuming that it's possible to do both. I think we will most likely want to just implment it the way YAGSL has it in their example though.

**Comment by willitcode** [comment]
Let's try implementing YAGSL's example implementation.
