### ISSUE TITLE
Implement Mailbox

### ISSUE THREAD

**Issue by QuackitsQuinn** [frc937/robot2024#9]
Implement the various subsystems for the mailbox along with commands. Don't forget to keep commands very *very* small

**Comment by willitcode** [comment]
Will actually want 3 subsystems:
- pneumatics (handles the pneumatic pistons that raise the mailbox)
- belts (handles the belts that drive the shooter part)
- mailbox (contains logic that applies to / handles both)
  - will want to instantiate versions of pneumatics and belts in here (probably)
  - we maybe don't actually need this one because we can do the same thing with command "compilations" (groups)

write a command that raises the intake and turns on the belt at the same time. you'll want to make a command that raises the intake, then make a command that turns on the belts, and then put them in a ParallelCommandGroup.

do all of your commands in separate classes

put all of the mailbox subsystems in a subfolder of the subsystems folder called "mailbox"

keep the commands in the base commands folder for now
